# Generated by Django 6.0.4 on 2026-05-05 08:59

import django.db.models.deletion
import visitors.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guard',
            name='shift',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Night', 'Night')], default='Morning', max_length=10),
        ),
        migrations.AddField(
            model_name='visitor',
            name='address_line',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='country',
            field=models.CharField(default='India', max_length=50),
        ),
        migrations.AddField(
            model_name='visitor',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='other_purpose',
            field=models.CharField(blank=True, help_text="Please specify if purpose is 'Other'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='person_to_meet',
            field=models.CharField(default='Amit', max_length=50),
        ),
        migrations.AddField(
            model_name='visitor',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='purpose',
            field=models.CharField(choices=[('Delivery', 'Delivery'), ('Meeting', 'Meeting'), ('Maintenance', 'Maintenance'), ('Personal Visit', 'Personal Visit'), ('Other', 'Other')], default='Delivery', max_length=50),
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_number', models.CharField(help_text='e.g., A-402, B-105', max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('is_committee_member', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuestPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_phone', models.CharField(max_length=15)),
                ('purpose', models.CharField(choices=[('Delivery', 'Delivery'), ('Meeting', 'Meeting'), ('Maintenance', 'Maintenance'), ('Personal Visit', 'Personal Visit'), ('Other', 'Other')], default='Delivery', max_length=50)),
                ('other_purpose', models.CharField(blank=True, help_text="Please specify if purpose is 'Other'", max_length=100, null=True)),
                ('pass_code', models.CharField(default=visitors.models.generate_pass_code, max_length=6, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_passes', to='visitors.resident')),
            ],
        ),
    ]
