# Generated by Django 6.0.4 on 2026-05-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_guard_shift_visitor_address_line_visitor_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestpass',
            name='address_line',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestpass',
            name='country',
            field=models.CharField(default='India', max_length=50),
        ),
        migrations.AddField(
            model_name='guestpass',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='guestpass',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
