# Generated by Django 6.0.4 on 2026-04-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_visitor_person_to_meet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='person_to_meet',
        ),
        migrations.AddField(
            model_name='visitor',
            name='other_purpose',
            field=models.CharField(blank=True, help_text="Please specify if purpose is 'Other'", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='purpose',
            field=models.CharField(choices=[('Delivery', 'Delivery'), ('Meeting', 'Meeting'), ('Maintenance', 'Maintenance'), ('Personal Visit', 'Personal Visit'), ('Other', 'Other')], default='Delivery', max_length=50),
        ),
    ]
