# Generated by Django 6.0.4 on 2026-04-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_remove_visitor_person_to_meet_visitor_other_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='person_to_meet',
            field=models.CharField(default='Amit', max_length=50),
        ),
    ]
