# Generated by Django 6.0.4 on 2026-04-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_visitor_person_to_meet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='other_purpose',
        ),
        migrations.AddField(
            model_name='guard',
            name='shift',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Night', 'Night')], default='Morning', max_length=10),
        ),
    ]
