# Generated by Django 6.0.4 on 2026-04-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_remove_visitor_other_purpose_guard_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='other_purpose',
            field=models.CharField(blank=True, help_text="Please specify if purpose is 'Other'", max_length=100, null=True),
        ),
    ]
