# Generated by Django 6.0.4 on 2026-04-30 10:53

import visitors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0006_visitor_other_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_name', models.CharField(help_text='The resident who created this pass', max_length=100)),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_phone', models.CharField(max_length=15)),
                ('pass_code', models.CharField(default=visitors.models.generate_pass_code, max_length=6, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
