# Generated by Django 6.0.4 on 2026-04-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0007_guestpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestpass',
            name='other_purpose',
            field=models.CharField(blank=True, help_text="Please specify if purpose is 'Other'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guestpass',
            name='purpose',
            field=models.CharField(choices=[('Delivery', 'Delivery'), ('Meeting', 'Meeting'), ('Maintenance', 'Maintenance'), ('Personal Visit', 'Personal Visit'), ('Other', 'Other')], default='Delivery', max_length=50),
        ),
    ]
