# Generated by Django 6.0.4 on 2026-05-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0009_remove_guestpass_resident_name_guestpass_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guard',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='guestpass',
            name='visitor_phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='resident',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
